
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'configBEGIN_BRACE BEGIN_CURVE_BRACE COMMA DATE END_BRACE END_CURVE_BRACE EQ INT IP4ADDR MACADDR ON QUOTEDSTR SEMICOLON SET STR TIME\n    config : section\n           | sections\n    \n    sections : sections section\n             | section\n    \n    section : STR IP4ADDR BEGIN_CURVE_BRACE items END_CURVE_BRACE\n            | ON STR BEGIN_CURVE_BRACE items END_CURVE_BRACE\n    \n    items : items item\n          | item\n    \n    item : STR STR STR SEMICOLON\n         | STR STR STR STR SEMICOLON\n         | STR QUOTEDSTR SEMICOLON\n    \n    item : STR INT DATE TIME SEMICOLON\n    \n    item : STR STR MACADDR SEMICOLON\n    \n    item : SET STR EQ QUOTEDSTR SEMICOLON\n         | SET STR EQ function SEMICOLON\n    \n    item : function SEMICOLON\n    \n    item : section\n    \n    item :\n    \n    function : STR BEGIN_BRACE args END_BRACE\n    \n    args : args COMMA arg\n         | arg\n    \n    arg : INT\n        | STR\n        | QUOTEDSTR\n        | function\n    '
    
_lr_action_items = {'BEGIN_BRACE':([16,31,39,],[22,22,22,]),'ON':([0,3,5,8,9,10,12,13,14,17,18,19,20,26,37,44,45,47,48,50,51,],[1,-4,1,-3,1,1,1,-17,-8,1,-16,-6,-7,-5,-11,-13,-9,-15,-14,-12,-10,]),'END_BRACE':([28,29,30,31,32,33,41,49,],[-25,-22,41,-23,-21,-24,-19,-20,]),'SET':([9,10,12,13,14,17,18,19,20,26,37,44,45,47,48,50,51,],[15,15,15,-17,-8,15,-16,-6,-7,-5,-11,-13,-9,-15,-14,-12,-10,]),'SEMICOLON':([11,25,35,36,38,40,41,43,46,],[18,37,44,45,47,48,-19,50,51,]),'INT':([16,22,42,],[23,29,29,]),'EQ':([21,],[27,]),'BEGIN_CURVE_BRACE':([6,7,],[9,10,]),'IP4ADDR':([4,16,],[7,7,]),'END_CURVE_BRACE':([9,10,12,13,14,17,18,19,20,26,37,44,45,47,48,50,51,],[-18,-18,19,-17,-8,26,-16,-6,-7,-5,-11,-13,-9,-15,-14,-12,-10,]),'MACADDR':([24,],[35,]),'COMMA':([28,29,30,31,32,33,41,49,],[-25,-22,42,-23,-21,-24,-19,-20,]),'STR':([0,1,3,5,8,9,10,12,13,14,15,16,17,18,19,20,22,24,26,27,36,37,42,44,45,47,48,50,51,],[4,6,-4,4,-3,16,16,16,-17,-8,21,24,16,-16,-6,-7,31,36,-5,39,46,-11,31,-13,-9,-15,-14,-12,-10,]),'TIME':([34,],[43,]),'DATE':([23,],[34,]),'QUOTEDSTR':([16,22,27,42,],[25,33,40,33,]),'$end':([2,3,5,8,19,26,],[0,-1,-2,-3,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'function':([9,10,12,17,22,27,42,],[11,11,11,11,28,38,28,]),'arg':([22,42,],[32,49,]),'config':([0,],[2,]),'section':([0,5,9,10,12,17,],[3,8,13,13,13,13,]),'args':([22,],[30,]),'item':([9,10,12,17,],[14,14,20,20,]),'items':([9,10,],[12,17,]),'sections':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> config","S'",1,None,None,None),
  ('config -> section','config',1,'p_config','parser.py',14),
  ('config -> sections','config',1,'p_config','parser.py',15),
  ('sections -> sections section','sections',2,'p_sections','parser.py',22),
  ('sections -> section','sections',1,'p_sections','parser.py',23),
  ('section -> STR IP4ADDR BEGIN_CURVE_BRACE items END_CURVE_BRACE','section',5,'p_section','parser.py',34),
  ('section -> ON STR BEGIN_CURVE_BRACE items END_CURVE_BRACE','section',5,'p_section','parser.py',35),
  ('items -> items item','items',2,'p_items','parser.py',42),
  ('items -> item','items',1,'p_items','parser.py',43),
  ('item -> STR STR STR SEMICOLON','item',4,'p_item','parser.py',56),
  ('item -> STR STR STR STR SEMICOLON','item',5,'p_item','parser.py',57),
  ('item -> STR QUOTEDSTR SEMICOLON','item',3,'p_item','parser.py',58),
  ('item -> STR INT DATE TIME SEMICOLON','item',5,'p_item_datetime','parser.py',70),
  ('item -> STR STR MACADDR SEMICOLON','item',4,'p_item_macaddr','parser.py',77),
  ('item -> SET STR EQ QUOTEDSTR SEMICOLON','item',5,'p_item_set','parser.py',84),
  ('item -> SET STR EQ function SEMICOLON','item',5,'p_item_set','parser.py',85),
  ('item -> function SEMICOLON','item',2,'p_item_function','parser.py',92),
  ('item -> section','item',1,'p_item_section','parser.py',99),
  ('item -> <empty>','item',0,'p_item_none','parser.py',106),
  ('function -> STR BEGIN_BRACE args END_BRACE','function',4,'p_function','parser.py',113),
  ('args -> args COMMA arg','args',3,'p_args','parser.py',120),
  ('args -> arg','args',1,'p_args','parser.py',121),
  ('arg -> INT','arg',1,'p_arg','parser.py',132),
  ('arg -> STR','arg',1,'p_arg','parser.py',133),
  ('arg -> QUOTEDSTR','arg',1,'p_arg','parser.py',134),
  ('arg -> function','arg',1,'p_arg','parser.py',135),
]
